### ISSUE TITLE
Problems on using pymodis to process modis data downloaded from nasa website.

### ISSUE THREAD

**Issue by funcgis** [lucadelu/pyModis#101]
I've downloaded a large number of Modis data from nasa website, while the data is only hdf documents available, the hdf.xml document is cannot be downloaded. 
Actually, I've tried to create tif documents from hdf by using pymodis, but it showed a mistaking hint of missing xml document,

**Comment by funcgis** [comment]
This is the command I use
![image](https://user-images.githubusercontent.com/33279866/35478733-34cb6546-0420-11e8-81f2-5c2f692157f5.png)

**Comment by madatx** [comment]
I have the same issue with parsemodis script trying to make parameters file for MOD09 products. It would be nice to add parser to .met files for NRT data.

**Comment by lucadelu** [comment]
XML files are required because they are useful to create the xml file for the mosaic file
