### ISSUE TITLE
downloading MODIS swath data?

### ISSUE THREAD

**Issue by mjklinger** [lucadelu/pyModis#104]
I'm trying to use pyMODIS to download MOD0HKM products from the LADDS DAAC over the entire Arctic region. Because this data is in swath and not tiled, I cannot feed the download script a region. Regardless of region specification, I also haven't had success downloading any of these MODIS products using pyMODIS.

**Comment by lucadelu** [comment]
Hi @mjklinger,I'm sorry but it is not possible download that product. You can download  only from server with the structure of https://e4ftl01.cr.usgs.gov/
