### ISSUE TITLE
Check for pygdal/osgeo before trying to install gdal as a dependency

### ISSUE THREAD

**Issue by raymond-grointel** [lucadelu/pyModis#105]
https://github.com/nextgis/pygdal offers a clean way to install gdal inside a virtualenv, and lists `osgeo` as a `package` in https://github.com/nextgis/pygdal/blob/31e7275/setup.py#L178

Please allow `pymodis` to check for `osgeo` before trying to install `gdal` as a dependency.

**Comment by raymond-grointel** [comment]
Can we have the v2.1.0 (c3d3d44) release on PyPI

**Comment by raymond-grointel** [comment]
![screenshot9](https://user-images.githubusercontent.com/34545687/86102647-7525f680-bac4-11ea-8fb9-48cb31c75625.png)

**Comment by lucadelu** [comment]
Done
