### ISSUE TITLE
Redundant printing from the package

### ISSUE THREAD

**Issue by vodp** [lucadelu/pyModis#116]
I think the following line should not be included, or alternatively, should be outputed via `logging`. Normal import of the package always show this line and it interferes with the output logic of the user-end's code.

https://github.com/lucadelu/pyModis/blob/18401b12711a403318d7bf8c209da4a9cbc8382c/pymodis/__init__.py#L18

**Comment by lucadelu** [comment]
What about the [Warnings library](https://docs.python.org/3.7/library/warnings.html)?

**Comment by lucadelu** [comment]
Should be fixed  with 39bc28aca425d1b70f633db85f318554de4b91d1

reopen if needed
