### ISSUE TITLE
modis_convert problem

### ISSUE THREAD

**Issue by monobakht** [lucadelu/pyModis#12]
Hi
I am using pyModis on a Windows7 x86 platform. As I am new to python programing, I have faced some problems and it would be highly appreciated if you can clear these queries for me:

1. I have installed the pyModis properly and it works with the example of full process scripts which is provided in pyModis webpage, except the last step (convert to GeoTIFF) which is crucial to me. When I run modis.convert.py with the required parameters I get immediately the error saying "pymodis_convert.py: error: You have to pass the name of HDF file."
I have double checked parameters with regard to misspelling and everything seems to be according to the documentation! here is my command which leads to this error:
modis_convert.py -s '( 1 1 1 1 1 1 1 1 1 1 1 1 )' -m F:\Software\MRT_download_Win -o F:\test_modis\finalfile.tif -g 250 F:\test_modis\outputfile.hdf

2. I need to download the data over a specific geographical region from this ftp address : ftp://ladsweb.nascom.nasa.gov/allData/6/MYD04_L2/
would you please kindly provide me with a sample command to download the data from above mentioned address? for example what would be the command in order to download this specific data : ftp://ladsweb.nascom.nasa.gov/allData/6/MYD04_L2/2005/004/MYD04_L2.A2005004.0925.006.2014024032926.hdf ?

Any help is greatly appreciated.
Mohamad

**Comment by lucadelu** [comment]
@monobakht could I close this issue? no answer after one year

**Comment by lucadelu** [comment]
please reopen if needed
