### ISSUE TITLE
MODIS_HDF to TIF

### ISSUE THREAD

**Issue by ZhouPeng1994** [lucadelu/pyModis#122]
RuntimeError                              Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\pymodis\convertmodis_gdal.py in _reprojectOne(self, l, quiet)
    246             dst_ds = self.driver.Create(out_name, self.dst_xsize,
--> 247                                         self.dst_ysize, 1, datatype)
    248         except:

C:\ProgramData\Anaconda3\lib\site-packages\osgeo\gdal.py in Create(self, *args, **kwargs)
   1689         """Create(Driver self, char const * utf8_path, int xsize, int ysize, int bands=1, GDALDataType eType, char ** options=None) -> Dataset"""
-> 1690         return _gdal.Driver_Create(self, *args, **kwargs)
   1691 

RuntimeError: Attempt to create new tiff file `C:\Users/XDQX/Downloads/TVDI/processed\MOD13A2.A2018257.h13v09.006.2018282125001_"1 km 16 days NDVI".tif' failed: No error

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-35-e3cc143971f7> in <module>
     16   fileout = osp.join(path, osp.basename(f)[:-4])
     17   extr = convertModisGDAL(f, fileout, subset, res=None, outformat='GTiff', epsg=4326)
---> 18   extr.run(quiet=True)
     19 
     20 # 检查转换的数据

C:\ProgramData\Anaconda3\lib\site-packages\pymodis\convertmodis_gdal.py in run(self, quiet)
    288             for i in self.subset:
    289                 if str(i) == '1':
--> 290                     self._reprojectOne(self.layers[n][0], quiet=quiet)
    291                 n = n + 1
    292             if not quiet:

C:\ProgramData\Anaconda3\lib\site-packages\pymodis\convertmodis_gdal.py in _reprojectOne(self, l, quiet)
    247                                         self.dst_ysize, 1, datatype)
    248         except:
--> 249             raise Exception('Not possible to create dataset %s' % out_name)
    250         dst_ds.SetProjection(self.dst_wkt)
    251         dst_ds.SetGeoTransform(self.dst_gt)

Exception: Not possible to create dataset C:\Users/XDQX/Downloads/TVDI/processed\MOD13A2.A2018257.h13v09.006.2018282125001_"1 km 16 days NDVI".tif

**Comment by lucadelu** [comment]
Dear @ZhouPeng1994,

sorry for the delay, did you fix the problem? I think the problem is in the output name, could you please send me the code that you use?

**Comment by ZhouPeng1994** [comment]
thanks，ｉhave solved the problem, there’s a problem with the outpath.

发自我的iPhone
