### ISSUE TITLE
WxPython missing, no GUI enabled

### ISSUE THREAD

**Issue by fadhli-atarita** [lucadelu/pyModis#124]
Hello,

I need to process MODIS data for my study and I found out about pymodis. I have installed every requirement but when i tried to run it, it gave me this message "WxPython missing, no GUI enabled". I tried to re-install wxpython using every method available but I still couldn't run the program (i have wxpython 4.0.7.post2). How can i solve this problem? I am using python 3.7.4 on a windows machine.

Thanks

**Comment by lucadelu** [comment]
Hi @fadhli-atarita,

did you follow this instructions http://www.pymodis.org/info.html#how-to-install-pymodis ?

I have now windows machine how to test. However you could you pyModis without GUI, it shoud be doable.

**Comment by lucadelu** [comment]
You can look also [this link](https://github.com/chingchai/workshop/tree/nump/pymodis#install-pymodis-on-windows-os-python3).

I'm going to close this issue; reopen if needed
