### ISSUE TITLE
The 'pyModis==2.1.0' distribution was not found

### ISSUE THREAD

**Issue by CGaffey** [lucadelu/pyModis#131]
I'm trying to run one of the example lines but I'm getting the following error though I just used git clone to install pyModis. I tried the pip route too but the same error occurs. I don't have an error for it when I do python > import pymodis. What should I try?

![image](https://user-images.githubusercontent.com/42742102/92039315-decfb480-ed42-11ea-8499-225d0c50e021.png)

**Comment by lucadelu** [comment]
I [uploaded it](https://pypi.org/project/pyModis/) right now, closing this issue. Reopen if needed
