### ISSUE TITLE
Project requires some support

### ISSUE THREAD

**Issue by anton-petrov** [lucadelu/pyModis#150]
Unfortunately, the project is no longer supported, as far as I can see.  
Perhaps we need to create a fork of the repository and continue support in it?

**Comment by anton-petrov** [comment]
@lucadelu

**Comment by geoschen** [comment]
realy?

**Comment by lucadelu** [comment]
Hi @anton-petrov,

the project is still supported, in the last month I was really busy with other stuff and I was not able to look at your code.

Thanks for the contributions

**Comment by anton-petrov** [comment]
Sounds great!

**Comment by lucadelu** [comment]
@anton-petrov if you are interested in contributions you are welcome

**Comment by anton-petrov** [comment]
Ok, will be glad to help with the project as far as possible
