### ISSUE TITLE
Maybe it's time to release v2.4.1?

### ISSUE THREAD

**Issue by anton-petrov** [lucadelu/pyModis#158]
@lucadelu 
Please, push an updated version to the PyPI.

**Comment by anton-petrov** [comment]
Not before https://github.com/lucadelu/pyModis/pull/159 will be merged.

**Comment by lucadelu** [comment]
I tried but I have a problem to compile because my GDAL version is too old (3.2.2). In the first days of September I'll update the OS and release the new version.
I would like to fix also #155 before release...

**Comment by lucadelu** [comment]
I release a new tag but I'm still unable to upload new version https://discuss.python.org/t/problem-uploading-new-version-ti-pypi-with-twine/42513

**Comment by lucadelu** [comment]
Finally I succeeded to upload 2.4.1 version to PyPi
