### ISSUE TITLE
Pymodis creatMosaic output missing

### ISSUE THREAD

**Issue by Rajasivaranjan** [lucadelu/pyModis#24]
I'm trying to use createMosaic function. It's working but i dont know where the output file is stored.
Kindly check out this.
This is what i used in Ipython 
>>>  convertmodis.createMosaic(listfile="E://listfileMOD11A1.005.txt", outprefix='out', mrtpath="E://", subset=False)
<pymodis.convertmodis.createMosaic instance at 0x0000000009E4E5C8>
where is the output??? Or else tell me how to use creatmosaic function in python. I need to mosaic 100 files.Kindly give ur suggestion as soon as possible.

Regards
Rajasivaranjan

**Comment by lucadelu** [comment]
The output file is saved in the current directory with out as prefix.

If you use pyModis 1.0.0 I suggest you to use createMosaicGDAL.

**Comment by Rajasivaranjan** [comment]
Thank u for the consideration,

The output is not creating, can u tell me how to do it?

**Comment by lucadelu** [comment]
The command gave you some error?

Are you sure that MRT is in the E:// directory, you should set the main directory of MRT.

Otherwise I could suggest you to use createMosaicGDAL of pyModis 1.0.0

**Comment by Rajasivaranjan** [comment]
Still i'm getting error.. Kindly resolve it

>>> import os, sys,glob
>>> from pymodis import convertmodis_gdal as pymod
>>> dest = "F:\\MODIS"
>>> files = glob.glob(os.path.join(dest, 'MOD*.hdf'))
>>> pymod.createMosaicGDAL(hdfnames = files, subset = None,
outformat='GTiff')
<pymodis.convertmodis_gdal.createMosaicGDAL instance at 0x000000000958F748>
>>> mq = pymod.createMosaicGDAL(hdfnames = files, subset = None,
outformat='GTiff')
>>> mq.run('test')

Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    mq.run('test.tif')
  File "build\bdist.win-amd64\egg\pymodis\convertmodis_gdal.py", line 610,
in run
    self.write_mosaic_xml(output)
  File "build\bdist.win-amd64\egg\pymodis\convertmodis_gdal.py", line 581,
in write_mosaic_xml
    pmm = parseModisMulti(listHDF)
  File "build\bdist.win-amd64\egg\pymodis\parsemodis.py", line 555, in
__init__
    self.parModis.append(parseModis(i))
  File "build\bdist.win-amd64\egg\pymodis\parsemodis.py", line 70, in
__init__
    raise IOError('{name}.xml does not exist'.format(name=self.hdfname))
IOError: F:\MODIS\MOD09A1.A2014145.h24v05.005.2014154101213.hdf.xml does
not exist
>>> files
['F:\\MODIS\\MOD09A1.A2014145.h24v05.005.2014154101213.hdf',
'F:\\MODIS\\MOD09A1.A2014145.h24v06.005.2014154103242.hdf',
'F:\\MODIS\\MOD09A1.A2014145.h25v05.005.2014154090943.hdf',
'F:\\MODIS\\MOD09A1.A2014145.h25v06.005.2014154090652.hdf']

**Comment by lucadelu** [comment]
Did you download also the xml files and they are in the same path of *files*?

The error tell you that F:\MODIS\MOD09A1.A2014145.h24v05.005.2014154101213.hdf.xml doesn't exist

The xml files are used for the metadata information

**Comment by Rajasivaranjan** [comment]
No i dont have xml file... i downloaded through linux terminal. i have all
the links in the text file and i simply download using wget..

**Comment by Rajasivaranjan** [comment]
But along with hdf files there is a supporting file in the same name with
extension .hdf.1

On Wed, Jan 21, 2015 at 4:37 PM, Raja Sivaranjan <rajasivaranjan92@gmail.com

**Comment by lucadelu** [comment]
You need both xml and hdf files... you could use pyModis also to download the files using [downmodis class](http://pymodis.fem-environment.eu/pymodis/downmodis.html)

**Comment by Rajasivaranjan** [comment]
Now I cant download once again sir. It's around 30 GB kindly suggest some
alternatives.

**Comment by lucadelu** [comment]
You should download only the xml files using wget adding *.xml* at the end of the hdf files name stored in you text file,

**Comment by Rajasivaranjan** [comment]
It's not downloading the link gets expired..

**Comment by lucadelu** [comment]
I don't know where do you download the data, but I think that you should be able to use pyModis to download them from http://e4ftl01.cr.usgs.gov/MOLT/MOD09A1.005/

**Comment by Rajasivaranjan** [comment]
The links were given in a text file as shown in the below;
I just used wget datafile.txt in linux terminal.So it download all the
files in the datafile.txt. And also i tried to download xml file by
inculding .xml in the last of each link, it's not working.

http://e4ftl01.cr.usgs.gov//MODIS_Composites/MOLT/MOD09A1.005/2014.05.25/MOD09A1.A2014145.h25v05.005.2014154090943.hdf
http://e4ftl01.cr.usgs.gov//MODIS_Composites/MOLT/MOD09A1.005/2014.05.25/MOD09A1.A2014145.h24v05.005.2014154101213.hdf
http://e4ftl01.cr.usgs.gov//MODIS_Composites/MOLT/MOD09A1.005/2014.05.25/MOD09A1.A2014145.h24v06.005.2014154103242.hdf
http://e4ftl01.cr.usgs.gov//MODIS_Composites/MOLT/MOD09A1.005/2014.05.25/MOD09A1.A2014145.h25v06.005.2014154090652.hdf

**Comment by lucadelu** [comment]
Clicking on your link I have no problem to download the data.

Also adding .xml it works for me, an example is this 

 http://e4ftl01.cr.usgs.gov//MODIS_Composites/MOLT/MOD09A1.005/2014.05.25/MOD09A1.A2014145.h25v05.005.2014154090943.hdf.xml

Sometime the NASA servers are down (more or less once a week), maybe did you find that time.

**Comment by Rajasivaranjan** [comment]
Thanks a lot. I ll try and reply the outcomes.

**Comment by Rajasivaranjan** [comment]
sir i hav downloaded the xml files. i want to reproject all files in UTM
projection system.  i'm not getting the syntax can u tell how to do it.

Thanks in advance
Rajasivaranjan

On Thu, Jan 22, 2015 at 4:10 PM, Raja Sivaranjan <rajasivaranjan92@gmail.com

**Comment by Rajasivaranjan** [comment]
I need to do both reprojection as well as mosaicking. I know to mosaic but
i'm struggling with reprojection. can u please tell me how to do it. I have
224 files to process.

On Thu, Jan 29, 2015 at 2:53 PM, Raja Sivaranjan <rajasivaranjan92@gmail.com
> wrote:

> sir i hav downloaded the xml files. i want to reproject all files in UTM
> projection system.  i'm not getting the syntax can u tell how to do it.
>
> Thanks in advance
> Rajasivaranjan
>
> On Thu, Jan 22, 2015 at 4:10 PM, Raja Sivaranjan <

**Comment by lucadelu** [comment]
With converModis/converModisGDAL you are able to reprojection

**Comment by lucadelu** [comment]
@Rajasivaranjan could this issue be considered closed?

**Comment by lucadelu** [comment]
please reopen if needed
