### ISSUE TITLE
Error when using FTP server

### ISSUE THREAD

**Issue by doncristobal** [lucadelu/pyModis#25]
Line 726 of downmodis.py throws the following error. There seems to be a typo: line 726 calls   self._downloadAllDaysFTP(), but the function is called  _downloadsAllDayFTP(self, days) (with 's' after 'download' but 'Day' instead of 'Days'.

----
AttributeError                            Traceback (most recent call last)
<ipython-input-28-cf552009d4af> in <module>()
----> 1 modisDown.downloadsAllDay()

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymodis/downmodis.pyc in downloadsAllDay(self, clean, allDays)
    724             self._downloadAllDaysHTTP(days)
    725         elif self.urltype == 'ftp':
--> 726             self._downloadAllDaysFTP(days)
    727 
    728     def _downloadAllDaysHTTP(self, days):

AttributeError: downModis instance has no attribute '_downloadAllDaysFTP'

**Comment by loganbyers** [comment]
This was a bug I introduced in a commit I made a while ago. My fork is synced to this master branch and has a bugfix for this problem. (efc14aaaabf5af47480e0f0c49ee8959f8364e3e)
