### ISSUE TITLE
FTP download: list index out of range

### ISSUE THREAD

**Issue by doncristobal** [lucadelu/pyModis#27]
List index out of range when calling downloadsAllDayFTP:
(Debugger tells me variable 'name' is a list containing this element: ['001'] )
Note: this is for FTP server ftp://ladsweb.nascom.nasa.gov/allData/51/MOD04_L2/

Traceback (most recent call last):
  File "/Users/username/Development/SunsetAnalysis/pyModisTestFromNASASite.py", line 63, in <module>
    modisDown.downloadsAllDay()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymodis/downmodis.py", line 726, in downloadsAllDay
    self._downloadAllDaysFTP(days)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymodis/downmodis.py", line 756, in _downloadAllDaysFTP
    listAllFiles = self.getFilesList()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymodis/downmodis.py", line 448, in getFilesList
    return self._getFilesListFTP()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymodis/downmodis.py", line 525, in _getFilesListFTP
    finalList = cicle_file()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymodis/downmodis.py", line 505, in cicle_file
    if self.tiles.count(name[3]) == 1 and jpeg:
IndexError: list index out of range

**Comment by loganbyers** [comment]
It might be good to share the code in pyModisTestFromNASASite.py so we can better understand how this error arrives. In particular it would be good to know how your downModis instance is setup.

**Comment by doncristobal** [comment]
I think this is the relevant code. Thanks for looking into it.

# NASA MODIS server
url = 'ftp://ladsweb.nascom.nasa.gov'
path = 'allData/51'
product = 'MOD04_L2'
user = 'anonymous'
password = 'email@email.com'
modisDown = downmodis.downModis(destinationFolder = dest, tiles = tiles, today = day, delta = delta,
                                url = url, path = path,
                                product = product, user = user, password = password, debug = False)

**Comment by doncristobal** [comment]
Sorry, I left out this part:

# destination folder
dest = "/tmp"
# tiles to download
tiles = "h18v05,h17v05"
# starting day
day = "2012-01-05"
# number of day to download
delta = 1

**Comment by lucadelu** [comment]
The problem is the structure of your repository.
The structure is different from the supported one, you can see the supported one [here](http://e4ftl01.cr.usgs.gov/MODIS_Composites/MOLT/MOD09A1.005/). This is the url ftp://ladsweb.nascom.nasa.gov/allData/51/MOD04_L2 of your repository as the same deep of the supported one, to see the difference.
I'm sorry, I could add your repository structure in the future (you could contribute adding it by yourself).

**Comment by doncristobal** [comment]
Thanks, I'll have to look into this.
Maybe you could add a note to the documentation pointing out which of the existing repositories are supported: http://modis.gsfc.nasa.gov/data/dataprod/

**Comment by doncristobal** [comment]
Luca, I see that - besides the different directory structure - the supported repository also has .xml files, which the atmosphere products at e.g. ftp://ladsweb.nascom.nasa.gov/allData/51/MOD04_L2/2012/005/ do not have - only HDF files.  Which role do the XML files play? Can the required information be extracted from the hdf files too? (I have some experience with netcdf4 and grib files, but haven't worked with hdf so far.)

**Comment by lucadelu** [comment]
The XML files contain metadata information. I'm looking for a solution to support also your repository but it is quite different from the supported one.

**Comment by lucadelu** [comment]
@doncristobal I just discovered the product your was looking to download is also present in a supported repository (https://e4ftl01.cr.usgs.gov/MOTA/MCD12Q1.051/) so you should be able to use pyModis to download the MCD12Q1 product.

So you could use something like

```
path = 'MOTA'
product = 'MCD12Q1.051'
user = 'YOURUSER'
password = 'YOURPASSWD'
dest = "/tmp"
tiles = "h18v05,h17v05"
day = "2012-01-01"
delta=1
modisDown = downmodis.downModis(destinationFolder = dest, tiles = tiles, today = day, delta = delta, path = path, product = product, user = user, password = password, debug = True)

```
