### ISSUE TITLE
downmodis log and list file empty

### ISSUE THREAD

**Issue by emmikb** [lucadelu/pyModis#28]
Hello,

I am having a hard time pulling data of the LP DAAC server with the downmodis command (run in Anaconda).  I've also tried to run the modis_download.py module from my command prompt and iPython but continually receive syntax errors (despite, in several cases, copying the examples from the pymodis website, with a path relevant to my computer)

`down = pymodis.downmodis.downModis(destinationFolder = 'C:\modis', password = 'password', user='username', url="http://e4ftl01.cr.usgs.gov", tiles = "h26v08", path = "MOLT", product = "MOD13Q1.005", today = "2014-01-01", enddate = "2014-02-02", jpg = False, debug = True, timeout = 30)`

I've replaced my actual password/username with 'password' and 'username'.  When I run this, the list and log files are created but they are empty.  I've played with the dates, but this has not helped.

Please advise and thanks.

**Comment by loganbyers** [comment]
I am not sure there is anything out of the ordinary, from what you have described. What is the remainder of your script? You need to use downModis.connect() to establish a link to the data server, and then the other functions to view which images and days are available for download and actually download them. Using downModis.connect() and debug=True should cause something to be written to the log. Try it out.

As a side note, downmodis works backwards from what one might imagine. The parameter 'today' is actually the last day chronologically, and enddate is the first day chronologically. Can't remember if there are problems if these two are swapped or if it automatically corrects for the right order of dates.

**Comment by emmikb** [comment]
Ok, when I call downModis.connect(), the log has the following:

`2015-02-02 12:02:31,463 - INFO - Starting new HTTP connection (1): e4ftl01.cr.usgs.gov
2015-02-02 12:02:31,655 - DEBUG - "GET /MOLT/MOD13Q1.005 HTTP/1.1" 301 252
2015-02-02 12:02:31,757 - DEBUG - "GET /MOLT/MOD13Q1.005/ HTTP/1.1" 200 None
`

I also swapped dates (`today = "2014-02-02", enddate = "2014-01-01"`)

Still nothing in the list file.  Could you possibly provide an example script showing the other functions to call?

**Comment by loganbyers** [comment]
Let's say you are trying to download files to local storage.

```Python
#make downloader
dm = pymodis.downmodis.downModis(destinationFolder=r"C:\modis",
    path="MOLT", product="MOD13Q1.005",tiles="h26v08",
    today = "2014-02-02", enddate = "2014-01-01")
dm.connect() 
print "Connection Attempts: " + str(dm.nconnection)

#get all files to download, for each day of interest
downloads = []
for day in dm.getListDays():
    print day
    files = dm.getFilesList(day)
    print files
    #make list of all the files 
    for f in files:
        downloads.append((f,day))
numDownload = len(downloads)
print "Files to Download: " + str(numDownload)

for filename, day in downloads:
print "DL: " + filename
dm.downloadFile(filename,r"C:\modis"+filename,day)
```

**Comment by lucadelu** [comment]
Hi, I used this code and it is working.
I only inverted the dates, because until 80b2983 enddate was the oldest date and today the newest.

```python
import pymodis
down = pymodis.downmodis.downModis(destinationFolder = '/tmp', url="http://e4ftl01.cr.usgs.gov", tiles = "h26v08", path = "MOLT", product = "MOD13Q1.005", today = "2014-02-02", enddate = "2014-01-01", debug = True)
down.connect()
down.downloadsAllDay()
```

**Comment by emmikb** [comment]
You guys are awesome - thanks.  

I've successfully downloaded the .hdf data and have converted it to reprojected .tifs using `pymodis.convertmodis_gdal.convertModisGDAL`.   This gave me a list of reprojected .tif files for each band in the .hdf images.  Two quick questions:

1.  I still need to mosaic and clip these tifs, but it looks like the mosaic function only works with .hdfs.  Do I simply need to mosaic the hdfs prior to running the `gdal.convertModisGDAL or is there a way to mosaic .tifs that I haven't uncovered?

2.  The parse.confResample function provides an option to clip (`bounds`), but I don't see this same option in the createMosaicGDAL or convert_modisGDAL functions.  How do I clip the .tifs (or, alternatively, should I clip the .hdfs)?

**Comment by lucadelu** [comment]
1. You should mosaic (using createMosaicGDAL) your data before and after convert them to TIF.
2. Sorry but I don't understand parse.confResample it is used to create the configuration file for MRT. It is not possible to clip the file. To clip them you could use gdalwarp. I was thinking (see #13) to add this capability but right now I have no time.

**Comment by emmikb** [comment]
One last question.  I've managed to get everything working, but when I convert my mosaicked (3-band) dataset, the converted output raster is only one band.  I'll need the other two bands for my analysis and I'm not sure why they are disappearing:   

 `i = 0`
  
`mosaic = pymodis.convertmodis_gdal.createMosaicGDAL(hdfnames= [filelist[i], filelist[i+1]], subset = '(1 1 0 0 0 0 0 0 0 0 0 1)', outformat = 'GTiff')`
`mosaic.run(str(filelist[i].split(".h")[0]) + 'mos.tif')`    
`mosaic.write_vrt(output = str(filelist[i].split(".h")[0]), separate = True)`
`convert = pymodis.convertmodis_gdal.convertModisGDAL(hdfname = str(filelist[i].split(".h")[0]) + 'mos.tif', prefix = 'test', subset = '(1 1 1)', res = res, outformat = 'GTiff', wkt = prj, resampl = 'NEAREST_NEIGHBOR', vrt = True)`
`convert.run_vrt_separated()`

Am I miss using the vrt commands or mis-specifying the subset in the convert line?

Thanks so much.

**Comment by lucadelu** [comment]
Hi, you have two way:
1. omit to run  mosaic.write_vrt and convert the data using convert.run()
2. run mosaic.write_vrt and after use convert.run_vrt_separated for each vrt file, if you choose three band you should find three vrt file

**Comment by emmikb** [comment]
I've tried this but I continually get an IndexError: list index out of range.  I think this has something to do with the subset, but my mosaicked GeoTiff has three bands, so the subset should be equal to '(1 1 1)' (i.e. convert all the bands of the mosaic).  

`mosaic = pymodis.convertmodis_gdal.createMosaicGDAL(hdfnames= [filelist[i], filelist[i+1]], subset = '(1 1 1)', outformat = 'GTiff')`

`mosaic.run(str(filelist[i].split(".h")[0]) + 'mos.tif')`

This gives me a three band unprojected mosaic of the .hdf data.  Then I convert this data:

`convert = pymodis.convertmodis_gdal.convertModisGDAL(hdfname = str(filelist[i].split(".h")[0]) + 'mos.tif', prefix = str(filelist[i].split(".h")[0]), subset = '(1 1 1)', res = res, outformat = 'GTiff', wkt = prj, resampl = 'NEAREST_NEIGHBOR', vrt = False)`

`convert.run()`

This is where the script throws an index error.  The script I sent in my last comment outputs a one-band Geotiff, correctly projected of the first band of the mosaicked (and unprojected) Geotiff I created with the mosaic function.

Once this is resolved things will be running smoothly.  Thanks for your patience and support.

**Comment by emmikb** [comment]
This is really the last question, promise!  Thanks so much for your help :)

**Comment by lucadelu** [comment]
Sorry for the delay in the answer; I think that if you create a GeoTiff with createMosaicGDAL you should be able to reproject the mosaic with gdalwarp. convertModisGDAL want a hdf as input probably this is the problem. 

Do you have some more info about the index error? the line where it happen or something similar...

**Comment by lucadelu** [comment]
@emmikb could I close this issue?

**Comment by emmikb** [comment]
Please do.  Sorry for the delay, I rarely check this email anymore.  Thanks..
 


     On Wednesday, September 16, 2015 8:08 PM, Luca Delucchi <notifications@github.com> wrote:
   

 @emmikb could I close this issue?—
