### ISSUE TITLE
pyModis GDAL HDF4 support

### ISSUE THREAD

**Issue by lpalao** [lucadelu/pyModis#30]
Dear Luca DeLucchi,

Good day!

I would want to use pyMODIS to download MODIS data but I am faced with some challenges. Could I ask for your guidance?

Here is the error message that I am receiving when running the code:

runfile('E:/Python_scripts/pyModis_download.py', wdir='E:/Python_scripts')
Traceback (most recent call last):
  File "<ipython-input-32-e2211f1b79c5>", line 1, in <module>
    runfile('E:/Python_scripts/pyModis_download.py', wdir='E:/Python_scripts')
  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 580, in runfile
    execfile(filename, namespace)
  File "E:/Python_scripts/pyModis_download.py", line 19, in <module>
    tiles='h26v06', path='MOLT', product='MOD13Q1.005', today=2015-01-01, enddate=2015-03-24)
  File "C:\Anaconda\lib\site-packages\pymodis\downmodis.py", line 272, in __init__
    raise IOError("GDAL installation has no support for HDF4, please"
IOError: GDAL installation has no support for HDF4, please update GDAL

In the end it says: GDAL installation has no support for HDF4, please update GDAL.

Then I tried to update my Python GDAL version using 
>>> pip install GDAL --upgrade

But it seems that my GDAL version is up-to-date. With regards to my GDAL core installer from GISinternals, I just downloaded and installed it this February 2015.

Could you help me trouble shoot this issue?

This is the code that I am trying to test.

import os
import pymodis
from pymodis import downmodis
ws = 'E:/Test'
#tile = 'h26v06'
#prod = 'MOD11C2.005'
#day = '2014-01-01'
#end = '2014-01-01'
pymodis.downmodis.downModis(ws, url='http://e4ftl01.cr.usgs.gov',\
tiles='h26v06', path='MOLT', product='MOD13Q1.005', today=2015-01-01, enddate=2015-03-24)

Thanks and all the best in your future development for pyMODIS.

**Comment by lucadelu** [comment]
Duplication of #29
