### ISSUE TITLE
Error using modis_mosaic.py

### ISSUE THREAD

**Issue by tr-gis** [lucadelu/pyModis#31]
I am getting used to the pymodis library by trying out the examples given on the page :  

(http://pymodis.fem-environment.eu/examples/full_example_gdal.html#downloading-data)

Using modis_download.py I managed to successfully download the .hdh files and the .xml files along with the text file listing them. Next I tried to mosaic them as in the example using modis_mosaic.py but I get the error as : 
![folder](https://cloud.githubusercontent.com/assets/12557720/7810812/f5766400-03c2-11e5-88f1-e33b6a507a09.png)

ERROR 4: `MOD11A1.A2012340.h29v05.005.2012342062359.hdf' does not exist in the file system,
and is not recognised as a supported dataset name.

The .hdf and .xml files are present in the directory, attaching snapshot of it too.
![folder1](https://cloud.githubusercontent.com/assets/12557720/7810815/f9ec8b68-03c2-11e5-891f-5d2132248a61.png)

**Comment by tr-gis** [comment]
Hey Luca, 
I guess I know why this error pops out :

So the script has been given a path to the text file but it doesn't realize that the .hdf files are to be searched in that directory itself and instead it searches for the files in the pymodis/scripts directory. I can say so because after I copied the .hdf files in the pymodis/scripts folder and then tried executing the command it worked perfectly.

I think this is because of the nature of python, where it searches for the files always in it's current directory unless otherwise explicitly specified like we specified the .txt file

Hope it makes sense. If you feel this is correct then please modify the script so that it searches for the .hdf files in the path  supplied.

**Comment by tr-gis** [comment]
I am sorry, the thing is that the .hdf files have to be in the same directory from where in your are running the commands. So changing to the directory that consists the .hdf files and then running the command works . IT NEED NOT NECESSARLIY BE pymodis/scripts directory

**Comment by lucadelu** [comment]
@tr-gis could I close this issue? I don't understand if it is solved or not

**Comment by tr-gis** [comment]
Yup. The issue has been solved. Thanks !!
