### ISSUE TITLE
modis_convert.py specifiying the subset

### ISSUE THREAD

**Issue by tr-gis** [lucadelu/pyModis#32]
Hello Luca,

The pymodis library is working great. Thank you for the awesome job :+1: . I just have some trouble with the modis_convert.py scripts. On the pymodis page it says that -- 

**"Using VRT format it create dataset of only one later, so you are forced to use -s "( 1 )" ".**

So I am trying to convert the .vrt files of the first two layers ie; -s '1 1 0 0'. I have two .vrt files after mosaicking the .hdf files now if I want to create the .tif files for the corresponding layers, how should I specify the subset here ? Is it goin to be like the same -s "(1 1)" or am I wrong ?

*Thanks *

**Comment by lucadelu** [comment]
If you want to convert to .tif why do you convert to .vrt?

You can use gdal_translate to convert .vrt to .tif.

**Comment by lucadelu** [comment]
@tr-gis did you solve your problem?

**Comment by lucadelu** [comment]
@tr-gis I'm closing because no answer, please reopen if needed
