### ISSUE TITLE
Problem with downmodis "Folder to store downloaded files does not exist or is not writeable"

### ISSUE THREAD

**Issue by Gundisalv** [lucadelu/pyModis#34]
Hello @lucadelu first of all congratulations on PyModis it is really useful. Now my issue, I'm triying to use downmodis inside my python script, it works but always says that the destination folder is not writable, but it is writable and if I use modis_download via cmd with the exact same parameters it works perfectly, wich could by the problem?

I'm working in Windows 7. The error refers to line 236 in downmodis.py

This are the lines.
****
        if os.access(destinationFolder, os.W_OK):
            self.writeFilePath = destinationFolder
        else:
            raise IOError("Folder to store downloaded files does not exist"
                          " or is not writeable")
***

If I execute in my python console "os.access(destinationFolder, os.W_OK)" it returns "true" so there should be no error.

Any thougths on what is happening?

Thanks.

**Comment by tr-gis** [comment]
I had previously done the same using a python script and it worked. Can you post your script so that we can see if there is anything wrong with that ?

**Comment by Gundisalv** [comment]
Hello @tr-gis yes! I forgot! here is it. Thanks.

from subprocess import os
import pymodis

destino = os.path.normpath('C:/Gonzalo/MOD09HIST')
if not os.path.exists(destino):
    os.makedirs(destino)

pymodis.downmodis.downModis(destino, password=None, user='anonymous',
                            url='http://e4ftl01.cr.usgs.gov', tiles= 
                            'h12v11, h12v12', path='MOLT', product=
                            'MOD09GQ.005', today=None, enddate=None, 
                            delta=1, jpg=False, debug=False,timeout=30)

**Comment by lucadelu** [comment]
Hi @Gundisalv,

This is really strange, I never had this kind of problem.

Can you write inside the folder?
Can you try to remove "os.path.normpath"?

Thanks 
Luca

**Comment by Gundisalv** [comment]
Hi @lucadelu ! thanks for your reply. Yes I can read/write in the folder, I use the "os.path.normpath" because I'm in Windows but even if I write the path as 'C:\\Gonzalo\\MOD09HIST' I get the same error.

Thanks,

Gonzalo

**Comment by lucadelu** [comment]
@Gundisalv  can you add import ipdb; ipdb.set_trace() before the if statement  and try to debug the problem? I really have no idea what is wrong. Could you try to use different python version?

**Comment by Gundisalv** [comment]
Hello @lucadelu ! I have no problem doing that, but I don't know exactly what to do.

Thanks ^_^!

**Comment by tr-gis** [comment]
Try this : 
import  os
import subprocess
subprocess.call('modis_download.py -r -s MOLT -p MOD09GQ.005 -t h12v11,h12v12 C:/Gonzalo/MOD09HIST',shell=True)

I used something like this in ubuntu and hence the way the destination folder is defined differed. If you are unable to solve the problem I would suggest you to move to Ubuntu 12.04 version. I have tried this before in Ubuntu and it worked perfectly.

~cheers

**Comment by lucadelu** [comment]
Hi @Gundisalv when ipdb console appear you are inside the code and you have no to set again the class downModis. 
When you have the console, you can run `os.access(destinationFolder, os.W_OK)` and see the output, if it's False, you can see `destinationFolder` variable and do other stuff to debug it.

You can read more [here](https://docs.python.org/2/library/pdb.html)

**Comment by Gundisalv** [comment]
Hi @lucadelu  I've tried that and the destination folder is ok and writable.

**Comment by lucadelu** [comment]
I'm sorry but I'm not able to replicate this error, @Gundisalv any good news?

**Comment by Gundisalv** [comment]
Hello @lucadelu ! sadly I could not get that fixed, I suppose it is a windows network error and I can not modify that here because of IT restrictions, so I decided to use wget to download the images. Anyway thank you very much, your work is good ^_^
