### ISSUE TITLE
Date range

### ISSUE THREAD

**Issue by CzendaZdenda** [lucadelu/pyModis#35]
When I want to download data for a some date range, I use parameters '-f' and '-e'. In documentation is written, that the '-f','--firstday' is 'the day to start download'. That's why I thought that when I want to download the data for example from 2013-01-01 to 2013-01-05 I would expect, that this command will do that:

`modis_download.py -r -t h20v01 -f 2013-01-01 -e 2013-01-05 E:\tmp\pymodis`

but after execute this command, in the destination folder are just files for four days (starting from 2013-01-02). Is that correct? When looking at the code, there are these lines downmodis.py>downModis>_getToday:

```
def _getToday(self):
        """Set the dates for the start and end of downloading"""
        ...
        # set delta
        if self.today and self.enday:
            if self.today < self.enday:
                today = self.enday
                enday = self.today
                self.today = today
                self.enday = enday
            delta = self.today - self.enday
            self.delta = abs(delta.days)
```
and then at [downmodis.py>downModis>getListDays]
```
def getListDays(self):
        """Return a list of all selected days"""
        self._getToday()

        today_s = self.today.strftime("%Y.%m.%d")
        # dirData is reverse sorted
        for i, d in enumerate(self.dirData):
            if d <= today_s:
                today_index = i
                break

        days = self.dirData[today_index:][:self.delta]
```
It means, that having the first day = 2013-01-01 and the end day = 2013-01-05, the self.delta variable is 4, not 5 as I would expect. And then at getListDays() method we get list of days counting from the end day and using delta = 4. That's why we have date range [2013-01-02:2013-01-05]. For me it looks strange. Should it behave like that?

**Comment by lucadelu** [comment]
This behavior was thought to solve some problem if last day is today, but I understand that this is quite strange.
The code could be rewritten like this

```python
def _getToday(self):
        """Set the dates for the start and end of downloading"""
        ...
        # set delta
        if self.today and self.enday:
            if self.today < self.enday:
                today = self.enday
                enday = self.today
                self.today = today
                self.enday = enday
            delta = self.today - self.enday
            self.delta = abs(delta.days) + 1
```

what do you think?

**Comment by CzendaZdenda** [comment]
I think, that it's ok. At least for me it looks more clear.

And by the way in python you can use something like that:
```python
self.today, self.enday = self.today, self.enday
```

**Comment by lucadelu** [comment]
ok, I will do that

I'm sorry I don't understand your suggestion, maybe you would like to write

```python
self.today, self.enday = self.enday, self.today
```

**Comment by CzendaZdenda** [comment]
Ups :) You are right :) Thanks! Also for pyModis!
