### ISSUE TITLE
OSError: [Errno 7] Argument list too long

### ISSUE THREAD

**Issue by leandroleal** [lucadelu/pyModis#37]
Hi,

I developed a python script to generated one tif file, with only one band, for each band contained in one hdf file, so:

**Code part** *(hosted in https://github.com/lapig-ufg/sitt/blob/master/src/tools/modis_acess.py)*:
```Python
for filename in os.listdir(self.targetPath):
  if filename.endswith(".hdf"):
	for spectralBase in self.__createSpectralBases():

		hdfFile = path.join(self.targetPath, filename)
		tifFile = path.join(self.targetPath, self.__createTifName(filename))

		modisParse = parsemodis.parseModis(hdfFile)
		confname = modisParse.confResample(spectral=spectralBase,
			output=tifFile)

		modisCover = convertmodis.convertModis(
			hdfname=hdfFile, confile=confname,
			mrtpath=self.mrtPath)

		modisCover.run()
```

**Image Input:**

* MOD13Q1.A2010209.h11v08.006.2015209150427.hdf 

**Image Output:**

* MOD13Q1.A2010209.h11v08.006.2015209150427.250m_16_days_blue_reflectance.tif
* MOD13Q1.A2010209.h11v08.006.2015209150427.250m_16_days_composite_day_of_the_year.tif
* MOD13Q1.A2010209.h11v08.006.2015209150427.250m_16_days_EVI.tif
* MOD13Q1.A2010209.h11v08.006.2015209150427.250m_16_days_MIR_reflectance.tif
* MOD13Q1.A2010209.h11v08.006.2015209150427.250m_16_days_NDVI.tif
* MOD13Q1.A2010209.h11v08.006.2015209150427.250m_16_days_NIR_reflectance.tif
* MOD13Q1.A2010209.h11v08.006.2015209150427.250m_16_days_pixel_reliability.tif
* MOD13Q1.A2010209.h11v08.006.2015209150427.250m_16_days_red_reflectance.tif
* MOD13Q1.A2010209.h11v08.006.2015209150427.250m_16_days_relative_azimuth_angle.tif
* MOD13Q1.A2010209.h11v08.006.2015209150427.250m_16_days_sun_zenith_angle.tif
* MOD13Q1.A2010209.h11v08.006.2015209150427.250m_16_days_view_zenith_angle.tif
* MOD13Q1.A2010209.h11v08.006.2015209150427.250m_16_days_VI_Quality.tif

BUT, when I run this script thousands and thousand of times (the goal is execute this for entire time-series, 2000 - 2015), I got this error:

**Error:**

```Python
Traceback (most recent call last):
  File "/data/lapig/DEV/repositories/satellite-image-time-series/src/modules/_module.py", line 49, in run
    result = self.process(message)
  File "/data/lapig/DEV/repositories/satellite-image-time-series/src/modules/modis.py", line 39, in process
    tmpPath=tmpPath, pathMrt=pathMrt);
  File "/data/lapig/DEV/repositories/satellite-image-time-series/src/modules/modis.py", line 59, in __downloadAndReproject
    modisAcess.reproject()
  File "/data/lapig/DEV/repositories/satellite-image-time-series/src/tools/modis_acess.py", line 65, in reproject
    modisCover.run()
  File "/usr/local/lib/python2.7/dist-packages/pymodis/convertmodis.py", line 85, in run
    subprocess.call([execut,'-p',self.conf])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
```

It's occurs because for each iteration the method checkMRTpath, [class convertmodis.py](https://github.com/lucadelu/pyModis/blob/master/pymodis/convertmodis.py), appends a repeated value in os.environ['PATH']:

```Python
def checkMRTpath(mrtpath):
    """Function to check if MRT path it correct
       :param str mrtpath: the path to MRT directory
       :return: The path to 'bin' and 'data' directory inside MRT path
    """
    if os.path.exists(mrtpath):
        if os.path.exists(os.path.join(mrtpath, 'bin')):
            mrtpathbin = os.path.join(mrtpath, 'bin')
            os.environ['PATH'] = "{path}:{data}".format(path=os.environ['PATH'],
                                                        data=os.path.join(mrtpath, 'data'))
        else:
            raise Exception('The path {path} does not exist'.format(path=os.path.join(mrtpath, 'bin')))
        if os.path.exists(os.path.join(mrtpath, 'data')):
            mrtpathdata = os.path.join(mrtpath, 'data')
            os.environ['MRTDATADIR'] = os.path.join(mrtpath, 'data')
        else:
            raise Exception('The path {path} does not exist'.format(path=os.path.join(mrtpath, 'data')))
    else:
        raise Exception('The path {name} does not exist'.format(name=mrtpath))
    return mrtpathbin, mrtpathdata
```

**Comment by leandroleal** [comment]
From 8975df2bc97b511bd85b936997685d94f9e267ae Mon Sep 17 00:00:00 2001
From: Leandro Leal Parente <leal.parente@gmail.com>
Date: Tue, 22 Dec 2015 09:40:35 -0200
Subject: [PATCH] FIX: append repeated value in os.environ['PATH']

---
 pymodis/convertmodis.py | 7 ++++---
 1 file changed, 4 insertions(+), 3 deletions(-)

diff --git a/pymodis/convertmodis.py b/pymodis/convertmodis.py
index 90559cf..52bd91b 100644
--- a/pymodis/convertmodis.py
+++ b/pymodis/convertmodis.py
@@ -46,10 +46,11 @@ def checkMRTpath(mrtpath):
        :return: The path to 'bin' and 'data' directory inside MRT path
     """
     if os.path.exists(mrtpath):
-        if os.path.exists(os.path.join(mrtpath, 'bin')):
-            mrtpathbin = os.path.join(mrtpath, 'bin')
-            os.environ['PATH'] = "{path}:{data}".format(path=os.environ['PATH'],
+        if os.path.exists(os.path.join(mrtpath,'bin')):
+            if os.environ['PATH'].find(os.path.join(mrtpath,'data')) == -1:
+              os.environ['PATH'] = "{path}:{data}".format(path=os.environ['PATH'],
                                                         data=os.path.join(mrtpath, 'data'))
+            mrtpathbin = os.path.join(mrtpath, 'bin')
         else:
             raise Exception('The path {path} does not exist'.format(path=os.path.join(mrtpath, 'bin')))
         if os.path.exists(os.path.join(mrtpath, 'data')):
-- 
2.4.3

**Comment by lucadelu** [comment]
Thanks a lot for the report.

I cannot understand the diff because the indentation is broken.

The problem about the limit is mostly related to the OS, you can read more about it [here](https://trac.osgeo.org/grass/ticket/2468)

**Comment by lucadelu** [comment]
@leandroleal can you provide me a non working example so I could test your code?

**Comment by leandroleal** [comment]
@lucadelu, I change my last post. 
If it isn't ok, I can send a email to you.
