### ISSUE TITLE
Use destinationPath in checkFile?

### ISSUE THREAD

**Issue by blindjesse** [lucadelu/pyModis#39]
It would be nice if `checkFile` automatically looked in `destinationPath` for the named hdf. Happy to send PR...

**Comment by lucadelu** [comment]
@blindjesse please send the PR, now I have not enough time

**Comment by lucadelu** [comment]
@blindjesse I was looking to solve this issue, but for me it seems already solved. `checkFile` obtain the HDF file path containing `destinationPath` already.

What do you want to modify?

**Comment by lucadelu** [comment]
@blindjesse could I clse this issue?

**Comment by blindjesse** [comment]
Yes
