### ISSUE TITLE
pymodis.downmodis issues python: nc4file.c:2696: NC4_open: Assertion `0' failed. Aborted

### ISSUE THREAD

**Issue by JFBazille** [lucadelu/pyModis#40]
Hi,

I tried to download with pymodis but it issues the following messages and simply quits iPython !

````
In [5]: import pymodis

In [6]: download = pymodis.downmodis.downModis("project/OUT/", product="MOD13Q1.005", 
tiles="h11v04", today="2015-04-04", delta=31)                                                                                                   

In [7]: download.connect()

In [8]: download.downloadsAllDay()
python: nc4file.c:2696: NC4_open: Assertion `0' failed.
Aborted  
```

The same error issues when I try to use modis_dowload.py

Have you ever meet this problem ?

**Comment by lucadelu** [comment]
Hi @JFBazille, 
No, i'm sorry but I'm not able to reproduce it

```
import pymodis
download = pymodis.downmodis.downModis("/tmp/", product="MOD13Q1.005", tiles="h11v04", today="2015-04-04", delta=31)
download.connect()
download.downloadsAllDay() 
```

And it download something

```
ls /tmp
-rw-r--r--  1 user   user    26K Apr 22 17:31 MOD13Q1.A2015081.h11v04.005.2015098095330.hdf.xml
-rw-r--r--  1 user   user      0 Apr 22 17:31 MOD13Q1.A2015081.h11v04.005.2015098095330.hdf
-rw-r--r--  1 user   user    950 Apr 22 17:31 modisMOD13Q1.005.log
```

What is your OS?
Did you check that error online?

**Comment by JFBazille** [comment]
My OS is a linux red hat.
I past this error on google but it gave very poor results...
It seems that is a problem with nc4file and hdf5 but I didn't know that pymodis uses netCDF4.

Thanks for the answer !

**Comment by lucadelu** [comment]
Please install hdf4 too, this is the right library for MODIS hdf, at least with gdal I'm usually able to use only hdf4.

Let me know.

**Comment by JFBazille** [comment]
Ho chiesto alla persona che si cura di python nel laboratorio, ha aggiunto
queste linee nella sistemazione di GDAL

# gdal
gdal_pkg='gdal-2.0.2'
wget http://download.osgeo.org/gdal/2.0.2/$gdal_pkg.tar.gz &&
tar xvfz $gdal_pkg.tar.gz
(
    cd $gdal_pkg
    ./configure --with-python --with-hdf5=yes --with-hdf4=yes
--prefix=$install_dir/inst --with-netcdf=$install_dir/inst && make -j8 &&
make install
)


e tutto funziona bene !

2016-04-22 21:18 GMT+02:00 Luca Delucchi <notifications@github.com>:
