### ISSUE TITLE
modis_mosaic.py: add support for multiple time stamps

### ISSUE THREAD

**Issue by neteler** [lucadelu/pyModis#47]
When downloading MODIS data of several days, the list file contains all of them. While this is fine, the modis_mosaic.py command does not respect this yet as it should generate multiple mosaiks with the timestamp in the resulting filename(s).

**Comment by lucadelu** [comment]
Please try to update pyModis version, if it works please close the issue

**Comment by lucadelu** [comment]
@neteler did you try the latest version?

**Comment by neteler** [comment]
I'm blocked with #66

**Comment by lucadelu** [comment]
@neteler please try now

**Comment by neteler** [comment]
Here some tests:

```
modis_mosaic.py -o mosaic_vrt -v listfileMOD11A1.006.txt

# a series of VRT files are generated:
ls -1 *.vrt | wc -l
36

# check for matching neighbor tiles:
grep hdf A2012003_mosaic_vrt_LST_Day_1km.vrt
			<SourceFilename relativeToVRT="0">HDF4_EOS:EOS_GRID:MOD11A1.A2012003.h18v03.006.2016102180740.hdf:MODIS_Grid_Daily_1km_LST:LST_Day_1km</SourceFilename>
			<SourceFilename relativeToVRT="0">HDF4_EOS:EOS_GRID:MOD11A1.A2012003.h18v04.006.2016102180755.hdf:MODIS_Grid_Daily_1km_LST:LST_Day_1km</SourceFilename>
```

While this is only a shallow test it looks fine. Thanks & closing.
