### ISSUE TITLE
warnings in WPS

### ISSUE THREAD

**Issue by lucadelu** [lucadelu/pyModis#54]
Warnings in WPS should be avoided

**Comment by chingchai** [comment]
Hello Luca,
I try execute downmodis wps service on web browser I found error **'WxPython missing, no GUI enabled'**

> 
XML Parsing Error: junk after document element
Location: http://localhost/cgi-bin/mm/zoo_loader_p3.cgi?request=Execute&service=WPS&version=1.0.0&Identifier=modisdownload&DataInputs=dns=/home/chingchai/lab-pyModis/lst_terra/;path=MOTA;tiles=h27v07;today=2015-01-01;enddate=2015-01-30;product=MCD43B4.005
WxPython missing, no GUI enabled

**Comment by lucadelu** [comment]
@chingchai yes I know, you have to fix it, I suggested you by email to add new variable to downModis class to suppress warning and any stdout print

**Comment by lucadelu** [comment]
This should be fixed with 39bc28aca425d1b70f633db85f318554de4b91d1 using warnings.

If needed, reopen
