### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print' : __init__.py

### ISSUE THREAD

**Issue by dhananjaymehta** [lucadelu/pyModis#55]
Log:

> > > import pymodis
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "~/anaconda/lib/python3.5/site-packages/pymodis/**init**.py", line 10
> > >     print "WxPython missing, no GUI enabled"
> > >                                            ^
> > > SyntaxError: Missing parentheses in call to 'print'

Solution: for Python 3.5 change line 10 as print ("WxPython missing, no GUI enabled")

**Comment by lucadelu** [comment]
This is fixed in branch 2.0, could you test it with python 3

**Comment by lucadelu** [comment]
Please reopen if needed
