### ISSUE TITLE
Downloading MODIS HDF files is not working when GDAL is not installed

### ISSUE THREAD

**Issue by kalxas** [lucadelu/pyModis#57]
I have tried to use master to download some files on Ubuntu Xenial.
Installation through pip fails due to GDAL, I had to remove GDAL from setup.py
But then, I find that download function is not working because of this:
https://github.com/lucadelu/pyModis/blob/master/pymodis/__init__.py#L5-L6
I had to comment out those lines to get download working again.

**Comment by lucadelu** [comment]
Yes in that two modules GDAL is mandatory, could we change the setup.py with a try condition? Maybe someone could need only download and MRT capabilities

**Comment by kalxas** [comment]
@lucadelu does this library work with GDAL 2.x?
I tested with python-gdal 2.1.0 and did not seem to recognize it.

**Comment by lucadelu** [comment]
@kalxas yes, I have python-gdal 2.1.0 and I have no problem

**Comment by kalxas** [comment]
@lucadelu which OS are you on?

**Comment by lucadelu** [comment]
@kalxas I'm on Debian testing

**Comment by kalxas** [comment]
Thanks, will look into it

**Comment by lucadelu** [comment]
I added this test be24b5b, problably we could close this ticket

**Comment by kalxas** [comment]
Thanks.
