### ISSUE TITLE
change order and naming of firstday and endday

### ISSUE THREAD

**Issue by initze** [lucadelu/pyModis#6]
1. I would propose to start the order chronologically, where first day is before endday (default: today)
It is just more intuitive (Ithink)

2. consistent naming for these two options
either firstdate/firstday - lastdate/lastday
or startdate/startday - enddate/endday

**Comment by lucadelu** [comment]
First implementation in 80b2983, should be backported to 1.0 branch

**Comment by lucadelu** [comment]
This capabilities is added in pyModis [version 1.0.1](https://github.com/lucadelu/pyModis/releases/tag/1.0.1)
