### ISSUE TITLE
pyModis windows 64 work around not working

### ISSUE THREAD

**Issue by kacasey** [lucadelu/pyModis#60]
I have not been successful getting pyModis in Windows going.  I have Anaconda python 2.7 installed.  Tried installing OSGeo4W (and pyModis) received "package missing in current win-64 channels" error(s for both).   I could not follow to completion the second windows work around.   Any other windows users successfully get pyModis working?

**Comment by lucadelu** [comment]
@kacasey sorry for delay, I'm sorry that is not working for you, but usually when I installed pyModis 	through OSGeo4W it works. 

I will try again when I will release pyModis 2.0 and I let you know.

I'm not a Windows user, but if you give me more info (OS, when you get the error) I will try to help you

**Comment by lucadelu** [comment]
Yesterday I installed pyModis on Windows 10 machine using the procedure suggested [here](http://www.pymodis.org/info.html#install-on-windows-with-osgeo4w)

**Comment by lucadelu** [comment]
@kacasey did you try again to install it?

**Comment by chingchai** [comment]
Hi @lucadelu and @kacasey I have tried installing pyModis 2.0.8 on Windows 10 through OSGeo4W64 it work for me. you can see [link](https://github.com/chingchai/workshop/tree/nump/pymodis#install-pymodis-on-windows-os-python3)

**Comment by lucadelu** [comment]
No activities since long time
