### ISSUE TITLE
modis.mosaic multiple layers sequence

### ISSUE THREAD

**Issue by cljohn91** [lucadelu/pyModis#61]
I am using modis.mosaic to mosaic a large batch of MOD13A2 tiles together.  However it seems that when including multiple layers in the -s argument the order of layers is not retained in the mosaic output.  For example using '-s "1 1 1 0 0 0 0 0 0 0 1 1" etc.' the mosaic output's first band is not NDVI (though NDVI is the first band in the MOD13A2 product).  Is there some method to the mosaic madness?  I couldn't find anything in the pyModis documentation...

**Comment by lucadelu** [comment]
Hi @cljohn91, sorry for delay in the answer.

You are right, the order was the right one (I don't know why and how nobody discovered the bug before).

It should be fixed in 3ee5a5b. Could you please test it?

**Comment by lucadelu** [comment]
@cljohn91 did you have time to test the latest version?

**Comment by cljohn91** [comment]
@lucadelu not yet; just saw your response yesterday.  I need to get the new version installed but I have the data to be modsaicked already so should be done by this weekend

**Comment by cljohn91** [comment]
@lucadelu The new version does output the proper number of bands, but now all layers of the resulting tif contains the same data (it appears to be the first layer selected in the -s argument)...

**Comment by cljohn91** [comment]
My mistake, I re-ran my code and everything worked as expected - this appears to be fixed.  One question - the naming conventions for my output files changed, while that part of my code was never altered... Have you run into this as well?  I use `subprocess.Popen('modis_mosaic.py -s "1 1 1 0 0 0 0 0 0 0 1 1" -o %s_%s_%s.tif %s' % ("NEWMosaic", year, day, outputbasename), shell=True)` and the resulting filename is `A2012129_NEWMosaic_2012_129.tif` and I don't know where the beginning "A2012129" is coming from.
