### ISSUE TITLE
Deactivate proxy to download 

### ISSUE THREAD

**Issue by guillaumecout** [lucadelu/pyModis#68]
Hi,
In order to download modis images, I have to deactivate the proxy server option in internet explorer otherwise I get this error:

    raise Exception("There are some troubles with the server. "
Exception: There are some troubles with the server. The directory seems to be empty

Is there a way to modify the python script so that I don't have to deactivate this option everytime I need to download images?

Thanks!

**Comment by lucadelu** [comment]
I think the problem is the same of #62, I close this issue and continue the discussion there
