### ISSUE TITLE
The Error not recognised as a supported file format

### ISSUE THREAD

**Issue by BKPSN** [lucadelu/pyModis#72]
I run the modis_download.py but the size of the  .hdf file is 0 K all along;
Could you please tell me why this happens and how to deal with it? Thanks a lot^_^

2016-10-14 22:57:52,059 - ERROR - `H:\Download\MOD09GA005\MOD09GA.A2016285.h14v00.005.2016287060338.hdf' not recognised as a supported file format.

**Comment by BKPSN** [comment]
My Python is Python 2.7 and my system is Windows 10

**Comment by lucadelu** [comment]
@BKPSN the problem could be that GDAL that it doesn't support HDF format, but I tried in a Docker container and I'm able to download it.

Are you sure that your password is working (some user discovered problem with strange character like $)? In the previous weeks some other user report some strange behavior on NASA server could you try again?

**Comment by BKPSN** [comment]
My old password contained a period(.), I deleted that period , changed to my campus network and tried it again ,now I can download the MODIS data successfully .In fact, I do not know the problem is caused by the period or network 。
I  will add the period into my password again to vertify this problem~
Thanks a lot ^_^.

**Comment by lucadelu** [comment]
@BKPSN thanks for testing it again, I'm going to close this ticket, if the period is the problem please open new ticket

**Comment by BKPSN** [comment]
I add the period and use my own network interface to try it again and it works !  Wonderful !
I think the problem maybe caused by NASA's server .
Thank you very much^_^Your Pymodis really really really helps me a lot !
