### ISSUE TITLE
download data over http

### ISSUE THREAD

**Issue by bucricket** [lucadelu/pyModis#74]
Hi,

I'm trying to download MODIS data using the API.  The following example does nothing.

mport os
import glob
from pymodis import downmodis

# destination folder
dest = "/tmp"
# tiles to download
tiles = "h18v04,h19v04"
# starting day
day = "2014-08-14"
# number of day to download
delta = 1

modisDown = downmodis.downModis(destinationFolder=dest, tiles=tiles, today=day,
                                delta=delta)

modisDown.connect()

I suspect its because I can't insert the user password.  I can download data using the command line version,  but I can enter the user password.  So how can I enter the user/password?

Thanks!
Mitch

**Comment by lucadelu** [comment]
Hi, 

downmodis.downModis has [password parameter](https://github.com/lucadelu/pyModis/blob/master/pymodis/downmodis.py#L228) 

did it help you?

**Comment by bucricket** [comment]
That only works for ftp it seems unless I didn’t understand correctly.

Mitch

**Comment by lucadelu** [comment]
@bucricket sorry I have to change to sentence, before was working only for FTP, now also for HTTP

**Comment by lucadelu** [comment]
fixed in 03ac7ba
