### ISSUE TITLE
ftplib.error_temp 

### ISSUE THREAD

**Issue by sylar11** [lucadelu/pyModis#84]
Hi all, why when I'm using the following command:

python /home/pyModis/scripts/modis_download.py -U user -P psw -p MOD09GQ -f 2017-04-01 -e 2017-04-19 -t h18v04,h19v04 -u ftp://nrt3.modaps.eosdis.nasa.gov -s allData/6/MOD09GQ/Recent/ -r MODIS/MOD09/GQ/2017/

I always get the following error:

_ftplib.error_temp: 421 Sorry, there are already 20 users from 46.18.27.62 logged on.  Try again in 10 minutes._

even if I have already waited for more than 3 hours between two consecutive runs of the command

Am I doing something wrong?

EDIT: I think I found the problem. It was related to URL I was trying to use. It seems that you can only use the one set as default: "https://e4ftl01.cr.usgs.gov"  (mind the "s" after http). After this change and setting the correct path to the file, it worked.

If I can suggest something, it would be great to avoid the _InsecureRequestWarning_ and the possibility to skip the file if it already exists in the destination folder

**Comment by lucadelu** [comment]
@sylar11 I'm happy that you solve the problem yourself, the *InsecureRequestWarning* should be removed with 2.0.5 version, and the capability to skip is already present (probably since the first version of pyModis).

I close this ticket, please open new one if needed
