### ISSUE TITLE
Continuing hdf4 problems

### ISSUE THREAD

**Issue by cljohn91** [lucadelu/pyModis#85]
@lucadelu I'm having a similar problem to other hdf threads, but those seem to have been resolved (see https://github.com/lucadelu/pyModis/issues/83). I'm using pymodis version 2.0.4, gdal version 1.11.5_2, and OSX El Capital version 10.11.6. Loading pymodis brings up the warning "GDAL installation has no support for HDF4, please update GDAL" which wasn't an issue for `modis_download.py`, but becomes problematic when trying to use `modis_mosaic.py` - it returns an error indicating that hdf is not a supported file format. In addition to this error, I get a warning that WxPython is missing - but I'm not on a Windows OS, and I don't care about the gui so my main concern is the HDF4 problem (My end goal is mosaicking, so this is a troubling roadblock). I ran `brew upgrade gdal` in bash to make sure gdal is up to snuff, and everything is fine on that front... Suggestions?

**Comment by lucadelu** [comment]
@cljohn91 this problem is usually not related to pyModis but to the packaging o gdal. If you try to investigate a HDF4 file using `gdalinfo` do you get an error? if you run `gdalinfo --formats` do you find HDF4 in the output list?

**Comment by cljohn91** [comment]
@lucadelu Thanks for the suggestion.  HDF4 is not included in the `gdalinfo --formats` command; as it turns out, hdf4 files are not by default supported in the homebrew gdal installation.  Working on figuring something out now... any tips?

**Comment by lucadelu** [comment]
Any tips I can give you is to read the documentation to build gdal
https://trac.osgeo.org/gdal/wiki/BuildingOnMac

**Comment by lucadelu** [comment]
@cljohn91 any updates? 

could you close the ticket since it is not a pyModis problem?

**Comment by cljohn91** [comment]
Yep, thanks for your help.  Still working out the gdal/hdf4 issue but I'll update once I have it figured out for posterity's sake.

**Comment by cljohn91** [comment]
Ok folks I finally figured it out.  Homebrew is a decided pain in the butt for getting hdf4 support on GDAL.  Instead, I'd recommend following the guidance of [this source](http://technical-notes-of-randerson-group.readthedocs.io/en/latest/gdal/).  Fought with this issue for weeks, and finally a single line of code takes care of everything in 15 minutes.  Just be sure to install MacPort to get things running smoothly.
