### ISSUE TITLE
modis_mosaic: it fails to create output

### ISSUE THREAD

**Issue by romulogoncalves** [lucadelu/pyModis#90]
Hi all, 

First congrats for pymodis, greate module. 

I would like to report a little issue. I have downloaded 17 HDF files, granualres for USA 2001 for MODIS Land cover dynamics and I list them in a file. Lets say: 2001.files

Then I call modis_mosaic to glue all this 17 HDF files into a GeoTiff

modis_mosaic.py -f GTiff -o 2001.tif 2001.files
WxPython missing, no GUI enabled
Traceback (most recent call last):
  File "/usr/local/bin/modis_mosaic.py", line 150, in <module>
    main()
  File "/usr/local/bin/modis_mosaic.py", line 144, in main
    modisOgg.run(output)
  File "/usr/local/lib/python2.7/dist-packages/pymodis/convertmodis_gdal.py", line 616, in run
    "created".format(name=self.out))
AttributeError: createMosaicGDAL instance has no attribute 'out'

root:modis# modis_mosaic.py --version
WxPython missing, no GUI enabled
GDAL 1.11.3, released 2015/09/16

Any feedback to solve the problem?

**Comment by romulogoncalves** [comment]
The same happens with latest version of GDAL:

root:modis# modis_mosaic.py --version
WxPython missing, no GUI enabled
GDAL 2.1.3, released 2017/20/01

**Comment by romulogoncalves** [comment]
Shouldn't we change line 616 of convertmodis_gdal.py from:
"created".format(name=self.out))
to
"created".format(name=output))

**Comment by lucadelu** [comment]
@romulogoncalves thanks a lot I should fixed it with fe9380d, could you try?

**Comment by romulogoncalves** [comment]
Hi, 

I have patched the code of the package I have installed with your changes and now it works.

Thanks for the quick fix.
