### ISSUE TITLE
no MODIS data downloaded

### ISSUE THREAD

**Issue by sylar11** [lucadelu/pyModis#91]
Hi, I'm using the following command to download MODIS data:

_/home/user/miniconda2/bin/python /home/pyModis/scripts/modis_download.py -U myuesrname -P my_psw -p MYD09GQ.006 -f 2017-07-16 -e 2017-07-19 -t h18v04,h19v04 -u https://e4ftl01.cr.usgs.gov -s MOLA/ -r -x /MODIS/MOD09/GQ/2017/_

but the only reply I got is 

**WxPython missing, no GUI enabled**

and no data are downloaded.

could you please tell me if there is something wrong?

thanks

**Comment by lucadelu** [comment]
@sylar11 it is working for me... did you [read and follow](http://www.pymodis.org/info.html#user-and-password) the manual to register correctly to NASA services?
  
These show you that the script is working

```
-rw-r--r--  1 lucadelu   lucadelu    81M Jul 19 09:36 MYD09GQ.A2017198.h18v04.006.2017200032055.hdf
-rw-r--r--  1 lucadelu   lucadelu    99M Jul 19 09:36 MYD09GQ.A2017198.h19v04.006.2017200033659.hdf
-rw-r--r--  1 lucadelu   lucadelu   8.4K Jul 19 09:36 MYD09GQ.A2017198.h19v04.006.2017200033659.hdf.xml
-rw-r--r--  1 lucadelu   lucadelu    85M Jul 19 09:38 MYD09GQ.A2017197.h19v04.006.2017199030622.hdf
-rw-r--r--  1 lucadelu   lucadelu   8.4K Jul 19 09:38 MYD09GQ.A2017197.h19v04.006.2017199030622.hdf.xml
-rw-r--r--  1 lucadelu   lucadelu   8.5K Jul 19 09:38 MYD09GQ.A2017197.h18v04.006.2017199025840.hdf.xml
```

**Comment by sylar11** [comment]
Ok, thanks for your suggestion. It did not saved the "Earthdata Search" application selection in “My application” tab.
thanks a lot for your support!!

**Comment by lucadelu** [comment]
@sylar11  so now it is working? could you close this ticket?

**Comment by sylar11** [comment]
Ok, thanks for your suggestion. It did not saved the "Earthdata Search" application selection in “My application” tab.
thanks a lot for your support!!

**Comment by sylar11** [comment]
The problem has been solved and the script is working fine now!
