### ISSUE TITLE
GDAL support for HDF4, but not via pyModis

### ISSUE THREAD

**Issue by cljohn91** [lucadelu/pyModis#92]
So I've finally figured out the HDF4 support for GDAL (see https://github.com/lucadelu/pyModis/issues/85), and running `gdalinfo --formats` includes HDF4 files as a supported format.  However, pyModis commands still yield an error `GDAL installation has no support for HDF4, please update GDAL`.  I'm not sure what to make of this, since I know GDAL is now installed properly.  Suggestions?

Versions:
Mac OSX El Capitan Version 10.11.6
GDAL 2.2.1, released 2017/06/23
pyModis Version: 2.0.6

**Comment by lucadelu** [comment]
Maybe the GDAL you installed and the one of Python is different... try open a python console and try

```python
import osgeo.gdal as gdal
import pymodis
gdal.GetDriverByName('HDF4')
```
You should get something like
```
<osgeo.gdal.Driver; proxy of <Swig Object of type 'GDALDriverShadow *' at 0x7faa10088180> >
```
If you get empty return this means that HDF4 is not installed in that python version

**Comment by cljohn91** [comment]
Hey Luca,

You're right, I'm getting a blank return on `gdal.GetDriverByName('HDF4')`.  Should I uninstall pyModis and start from scratch, or is there some way I can point python's gdal to the hdf4 driver that comes up with `gdalinfo --formats`?

**Comment by cljohn91** [comment]
Figured it out.  See the full solution [here](https://stackoverflow.com/questions/45440927/gdal-works-in-bash-but-not-python?noredirect=1#comment77943881_45440927).  Long story short, I removed some old redundant gdal packages, and used conda to install hdf4, proj4, and gdal among other libraries.
