### ISSUE TITLE
The output file of createMosaicGDAL

### ISSUE THREAD

**Issue by sunshine1204** [lucadelu/pyModis#93]
Hello Luca, I need your help after the following question botherd me for many days. Thank you !

#1. question: The output .hdf file (one file) used by createMosaicGDAL contains 1200 subsetdatas when I open it in ArcMap, and when I open the mosaicked .hdf file using "gdal  GetSubDatasets() ", its result is null list (i.e. [ ]). So,I can't continue to do next work (reprejection). Do you have any good  solutions  or suggestions?
#2. my code:
from pymodis import convertmodis_gdal as pymod
import os, glob
import numpy as np
day= 2015017
enddate= 2015001
dest=  "D:\\Test\\NDVI\\" #original NDVI files: 3 titles files, 1200*1200 per title .hdf file
for iday in range(enddate,day,16):	
	files= glob.glob(os.path.join(dest, 'MOD13A2.A'+str(iday)+'*.hdf'))	
	output= 'D:\\Test\\NDVI\\Mosaic\\Mosaic_'+ str(iday)+'.hdf' 	
	outformat= 'HDF4Image'	
	subset=[1,1,0,0,0,0,0,0,0,0,0,1] # 3 layers shoud be mosaicked(ndvi,evi,viq)
	modis_mosaic= pymod.createMosaicGDAL(hdfnames= files, subset= subset, outformat= outformat)
	modis_mosaic.run(output)

Looking forward to your reply! Thank you again!

**Comment by lucadelu** [comment]
Dear @sunshine1204 , sorry for delay I lost your question...
#1 no sorry, I have no a good solution but...
#2 createMosaicGDAL should be used to mosaic different tiles of the same day and not from different days, probably this could also solve the previous problem

**Comment by sunshine1204** [comment]
Hello Luca, that's all right. Glad to receive your reply.  In actually,  "CreateMosaicGDAL" has been applied to mosaic different tiles of the same day in my codes.
